---
apiVersion: v1
kind: Namespace
metadata:
  name: tasks-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tasks-api
  name: deployment-tasks
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-tasks
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-tasks
    spec:
      containers:
      - image: 830931683151.dkr.ecr.us-east-1.amazonaws.com/tasks-api:latest
        imagePullPolicy: Always
        name: app-tasks
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: tasks-api
  name: service-tasks
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-tasks
